name = 'np_rw_buffer'
version = '1.1.7'
description = 'Library to help store audio data in a circular buffer.'
url = 'https://github.com/justengel/np_rw_buffer'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
